/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import com.google.gson.*;
import com.google.gson.stream.JsonReader;
import SIdP.*;
import SPos.*;
import java.io.*;
import java.net.*;

/**
 *
 * @author root
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }
    public void cargarIDP(Identificacion id){
	jNombre.setText(id.getNombre());
	jApellido.setText(id.getApellido());
	jEstado.setText(id.getEstado());
	jFecha.setText(id.getFecha());
	jEstadoC.setText(id.getEstado_c());
	jCuidadNac.setText(id.getCiudad_nac());
	jCuidadAct.setText(id.getCiudad_act());
	jProfesion.setText(id.getProfesion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCI = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPosi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jEstado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jEstadoC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCuidadNac = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCuidadAct = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jProfesion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lPerfil = new javax.swing.JLabel();
        lCara = new javax.swing.JLabel();
        lCuerpo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jLabel1.setText("CI");
        jPanel1.add(jLabel1);
        jPanel1.add(jCI);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jPanel1.add(jLabel13);

        jLabel14.setText("Posicion(x,y):");
        jPanel1.add(jLabel14);
        jPanel1.add(jPosi);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2);
        jPanel2.add(jNombre);

        jLabel3.setText("Apellido:");
        jPanel2.add(jLabel3);
        jPanel2.add(jApellido);

        jLabel4.setText("Estado:");
        jPanel2.add(jLabel4);
        jPanel2.add(jEstado);

        jLabel5.setText("Fecha:");
        jPanel2.add(jLabel5);
        jPanel2.add(jFecha);

        jLabel6.setText("Estado Civil:");
        jPanel2.add(jLabel6);
        jPanel2.add(jEstadoC);

        jLabel8.setText("Ciudad de Nacimiento:");
        jPanel2.add(jLabel8);
        jPanel2.add(jCuidadNac);

        jLabel7.setText("Ciudad Actual:");
        jPanel2.add(jLabel7);
        jPanel2.add(jCuidadAct);

        jLabel9.setText("Profesion:");
        jPanel2.add(jLabel9);
        jPanel2.add(jProfesion);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 30, 10));

        lPerfil.setText("Perfil");
        jPanel3.add(lPerfil);

        lCara.setText("Cara");
        jPanel3.add(lCara);

        lCuerpo.setText("Cuerpo");
        jPanel3.add(lCuerpo);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Socket unSocket = null;
        PrintWriter out = null;
        BufferedReader in = null;

        try {
            unSocket = new Socket("localhost", 2019);
            // enviamos nosotros
            out = new PrintWriter(unSocket.getOutputStream(), true);

            //viene del servidor
            in = new BufferedReader(new InputStreamReader(unSocket.getInputStream()));

            BufferedReader stdIn = new BufferedReader(new InputStreamReader(System.in));
            String fromServer;
            String fromUser;

            if ((fromServer = in.readLine()) != null) {
                System.out.println("Servidor: " + fromServer);
                

                fromUser = jCI.getText();
                if (fromUser != "") {
                    
                    
                    System.out.println("Cliente: " + fromUser);

                    //escribimos al servidor
                    out.println(fromUser);
                }
		Gson gson = new Gson();
		String SidP = in.readLine();
		if(SidP!="{}"){
			
			JsonReader reader = new JsonReader(new StringReader(SidP));
			reader.setLenient(true);
			Identificacion id = gson.fromJson(reader,Identificacion.class);
			cargarIDP(id);	
		}
		String[] img = new String[3];
		img[0] = in.readLine();
		img[1] = in.readLine();
		img[2] = in.readLine();
		
		String Posicion = in.readLine();
		if(Posicion!="{}"){
			JsonReader reader = new JsonReader(new StringReader(Posicion));
			reader.setLenient(true);
			Posicion pos = gson.fromJson(reader,Posicion.class);
			jPosi.setText(pos.getPosi());
			
		}
		
		
                
            }

            out.close();
            in.close();
            stdIn.close();
            unSocket.close();
        } catch (UnknownHostException e) {
            System.err.println("Host desconocido");
            System.exit(1);
        } catch (IOException e) {
            System.err.println("Error de I/O en la conexion al host");
            System.exit(1);
        }



    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jEstado;
    private javax.swing.JTextField jApellido;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCI;
    private javax.swing.JTextField jCuidadAct;
    private javax.swing.JTextField jCuidadNac;
    private javax.swing.JTextField jEstadoC;
    private javax.swing.JTextField jFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPosi;
    private javax.swing.JTextField jProfesion;
    private javax.swing.JLabel lCara;
    private javax.swing.JLabel lCuerpo;
    private javax.swing.JLabel lPerfil;
    // End of variables declaration//GEN-END:variables
}
